server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodcourt_plaza
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "FoodCourt plaza microservice"
appVersion: "1.0.0"
