server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/foodcourt_plaza
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  token:
    validity: 18000
    prefix: Bearer
  signing:
    key: signingkey
  authorities:
    key: roles
  header:
    string: Authorization

appDescription: "FoodCourt plaza microservice"
appVersion: "1.0.0"
